### ISSUE TITLE
[Feature Request] Installation guide

### ISSUE THREAD

**Issue by m-mattia-m** [andrii-kryvoviaz/slink#28]
First of all, this project looks great and it would be great if some of the features you mentioned (built-in S3 provider, admin board, dashboards, DB support for e.g. MySQL) were implemented.

However, I probably missed something, but I wasn't able to set up Slink locally. To be precise, I was able to set it up, but I couldn't register a user. I always get the error: "Something went wrong. Please try again later" and in the docker console logged these message: "WARNING Context::compress(): Unknown compression method". What do I need to do to fix this problem?

```yaml
services:
  slink:
    image: anirdev/slink:latest
    container_name: slink
    environment:
      - ORIGIN=http://localhost:3000
      - USER_APPROVAL_REQUIRED=false
      - USER_PASSWORD_MIN_LENGTH=8
      - USER_PASSWORD_REQUIREMENTS=15
      - IMAGE_MAX_SIZE=15M
      - STORAGE_PROVIDER=local
    ports:
      - "3000:3000"
    volumes:
      - slink_data:/app/var/data
      - slink_images:/app/slink/images

volumes:
  slink_data:
  slink_images:
```

**Comment by andrii-kryvoviaz** [comment]
Your configuration looks good. A recent release introduced an issue, which has been addressed in version `1.2.1`. Everything should work as expected now.

**Comment by geek2024811** [comment]
docker run 
![image](https://github.com/user-attachments/assets/5bd9df47-0d33-4bb5-b60f-1ff81c4be3e3)

**Comment by godpowerscn** [comment]
I'm having the exact same issue and it's heartbreaking.

**Comment by m-mattia-m** [comment]
It now works with the new version v1.2.1. Thanks for fixing this issue so quickly.

**Comment by seramat** [comment]
> docker run ![image](https://private-user-images.githubusercontent.com/173036424/373918404-5bd9df47-0d33-4bb5-b60f-1ff81c4be3e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzYyNzcsIm5iZiI6MTcyODM3NTk3NywicGF0aCI6Ii8xNzMwMzY0MjQvMzczOTE4NDA0LTViZDlkZjQ3LTBkMzMtNGJiNS1iNjBmLTFmZjgxYzRiZTNlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDcyYmZkZTI2ODliNDE1NzYzZDNiZjRlYzQyOTQxNmQxYmFjMjI1MWVkNTUyMDdkY2Q3ZDkyOWY0ZGUyNmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mxAeHHtPkGafgHuHDHpyZrLA3OOOGQdBNItWBfV5368)

I have the same problem. How to check the installed version and update to v1.2.1 in docker compose?

**Comment by m-mattia-m** [comment]
I'm not sure if I understand you correctly, but you only have to change the tag from `latest` to `v1.2.1`

```yaml
services:
  slink:
    image: anirdev/slink:v1.2.1
```

You can check with `docker images anirdev/slink` which tags/versions are installed.
