### ISSUE TITLE
[Feature Request] Please add custom PORT parameter

### ISSUE THREAD

**Issue by mike-zarandona** [andrii-kryvoviaz/slink#46]
This would make it loads easier for anyone to run Slink alongside other containers without the hassle of rebuilding

**Comment by andrii-kryvoviaz** [comment]
You may just remap any port with docker `-p` flag or docker compose `ports` setting (`<your_port>:3000`). Will it solve the issue?

Alternatively, if you are using traefik as a reverse proxy, you may omit mapping the ports at all, e.g.:
```yaml
# docker compose traefik example
services:
  slink:
      image: anirdev/slink:latest
      container_name: slink
      restart: always
      environment:
        - ORIGIN=https://share.anir.cloud
      volumes:
        - ./data/slink/var/data:/app/var/data
        - ./data/slink/images:/app/slink/images
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.slink.entrypoints=http"
        - "traefik.http.routers.slink.rule=Host(`share.anir.cloud`)"
        - "traefik.http.middlewares.slink-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.slink.middlewares=slink-https-redirect"
        - "traefik.http.routers.slink-secure.entrypoints=https"
        - "traefik.http.routers.slink-secure.rule=Host(`share.anir.cloud`)"
        - "traefik.http.routers.slink-secure.tls=true"
        - "traefik.http.routers.slink-secure.service=slink"
        - "traefik.http.services.slink.loadbalancer.server.port=3000"
        - "traefik.docker.network=proxy"
      networks:
        - proxy
```

**Comment by mike-zarandona** [comment]
This does not solve my issue, unfortunately.  I am not using Traefik.

The issue is a local system can only host a single service on an internal port.  LOTS of docker images default to port 3000, and to expose an environment `PORT` variable would allow quick and easy remapping when someone is running many services on their system.  Currently I have another image which runs by default on port 3000 which I'm unable to change.

I'm happy to make a PR if that's helpful

**Comment by andrii-kryvoviaz** [comment]
As I mentioned above, you may remap any ports just simply altering your docker run command:

```exec
docker run -p 3001:3000 anirdev/slink:latest
```

Where instead of `3001` you can use any available port on the host. 

Or docker compose config:

```yaml
services:
  slink:
      image: anirdev/slink:latest
      ports: 
          - "3001:3000"
```

That should work. Are there any other hidden implications which I don't see related to your setup?
