### ISSUE TITLE
Unable to create first user

### ISSUE THREAD

**Issue by shutchi2** [andrii-kryvoviaz/slink#49]
Just installed for first time on unraid, my first app on unraid, and I'm unable to create the first user. Is there a default admin account or something else I'm missing?

**Comment by andrii-kryvoviaz** [comment]
Unfortunately, no. There is no default user.
Are there any log messages in the console?

**Comment by shutchi2** [comment]
No messages at all in the console.

**Comment by pollin-zhu** [comment]
@shutchi2 @andrii-kryvoviaz 

I got same issue. Here is what's in console:

2025-05-31 21:05:39,542 WARN exited: startup (exit status 14; not expected)

2025-05-31 21:05:39,542 WARN exited: redis (exit status 1; not expected)

2025-05-31 21:05:39,598 WARN exited: symfony_about (exit status 14; not expected)

2025-05-31 21:05:41,601 INFO spawned: 'redis' with pid 36

2025-05-31 21:05:41,610 WARN exited: redis (exit status 1; not expected)

2025-05-31 21:05:44,615 INFO spawned: 'redis' with pid 44

2025-05-31 21:05:44,625 WARN exited: redis (exit status 1; not expected)

2025-05-31 21:05:45,626 INFO gave up: redis entered FATAL state, too many start retries too quickly

---
Here is the screenshot when I failed to create a new/first user:

![Image](https://github.com/user-attachments/assets/49def25d-6f21-4a4e-9674-0ce7087eb25f)

**Comment by pollin-zhu** [comment]
I gave a try for v1.4.7 + v1.4.8 and v1.4.9, same issue

**Comment by andrii-kryvoviaz** [comment]
@pollin-zhu is this instance also run on unraid?

May you also share your configuration (docker, docker compose)?

**Comment by pollin-zhu** [comment]
I'm running it on my QNAP's NAS, a docker.

![Image](https://github.com/user-attachments/assets/62706977-9231-49bb-ba4e-4445a65325af)

**Comment by andrii-kryvoviaz** [comment]
@pollin-zhu looks good to me. Make sure that you have the correct permissions on the mounted volumes. Based on the console output you provided, my first assumption is that, for some reason, there is an issue with the database, which is stored on a mounted volume (if you followed the example from the docs).

**Comment by pollin-zhu** [comment]
@andrii-kryvoviaz , that's a good point. I doubted the permission/setting was right since I found there was nothing in data folder.

Here is the permission for my volumns:
data: 

![Image](https://github.com/user-attachments/assets/42289cfa-2c9d-4b5e-9441-09d63c987c16)

images: 

![Image](https://github.com/user-attachments/assets/fa1a1c42-c7f0-462e-8fc3-25088b5ac2bb)

mappings: 

![Image](https://github.com/user-attachments/assets/0aa94bb8-cfca-4c37-a890-826526520358)

**Comment by pollin-zhu** [comment]
I may know what's the root cause. the mount point should be '/app/var/...'  instead of '/...'. Let me fix it.

![Image](https://github.com/user-attachments/assets/c94406cc-b8c2-4e1b-b553-cb99b602df54)

**Comment by pollin-zhu** [comment]
@andrii-kryvoviaz , it works!

2025-06-01 06:24:04,309 INFO supervisord started with pid 1
2025-06-01 06:24:05,311 INFO spawned: 'client-app' with pid 7
2025-06-01 06:24:05,314 INFO spawned: 'redis' with pid 8
2025-06-01 06:24:05,316 INFO spawned: 'startup' with pid 9
2025-06-01 06:24:05,318 INFO spawned: 'swoole-runtime' with pid 10
2025-06-01 06:24:05,323 INFO spawned: 'symfony_about' with pid 11
2025-06-01 06:24:05,328 INFO success: startup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
[Startup] Skipping creation of Projection Database as DATABASE_URL uses SQLite.
[Startup] Skipping creation of Event Store Database as ES_DATABASE_URL uses SQLite.
Listening on 0.0.0.0:4066
2025-06-01 06:24:06,790 INFO success: client-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-06-01 06:24:06,790 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-06-01 06:24:06,790 INFO success: swoole-runtime entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-06-01 06:24:06,790 INFO success: symfony_about entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 [OK] Successfully migrated to version:                                         
      Slink\Shared\Infrastructure\Persistence\EventStore\Migrations\Version20231
      029174455                                                                 
2025-06-01 06:24:06,898 WARN exited: symfony_about (exit status 1; not expected)
 [OK] Successfully migrated to version:                                         
      Slink\Shared\Infrastructure\Persistence\Doctrine\Migrations\Version2024101
      6200959                                                                   

 [OK] Done!                                                                     

2025-06-01 06:24:07,592 INFO exited: startup (exit status 0; expected)

**Comment by pollin-zhu** [comment]
@andrii-kryvoviaz another issue:

i created a user successfully and also activated/granted it as Admin, but once I signed in, nothing happened and it's always in guest user. (account is right: when i input wrong password, there was error message).

i checked logs, but there is no new ones besides the system start related logs

**Comment by pollin-zhu** [comment]
@andrii-kryvoviaz Here is my finding.

After signed in, there was related cookies generated with a very short lifecycle (createdUserId was empty, it's interesting)

![Image](https://github.com/user-attachments/assets/560a141f-af12-4e1f-b19d-7c44b1560688)

![Image](https://github.com/user-attachments/assets/13b3b501-f2db-427e-8bfc-bdd90a85d730)

but in the next following request, the request payload didn't include any cookie and i checked cookies for this site, it's empty

![Image](https://github.com/user-attachments/assets/c7ff5d2b-da8a-496e-bb12-cf6922d98d76)

BTW, you can check my ENV from my repliy above. just paste one: 
ORIGIN=http://pollin.myqnapcloud.com:14166

How to enable DEBUG log to dig more clues?

**Comment by hypr88** [comment]
@andrii-kryvoviaz 
i also agree, i cannot register the first user nor login. pretty sad cause would be the perfect solution for me...
My compose-data from portainer

version: "3.9"
services:
  slink:
    image: anirdev/slink:latest
    container_name: Slink
    environment:
      ORIGIN: https://schnappschuss.veithhummel.de
      USER_APPROVAL_REQUIRED: false #or #true Require user approval before they can upload images
      STORAGE_PROVIDER: local
    volumes:
      - /volume1/docker/slink/data:/app/var/data:rw
      - /volume1/docker/slink/images:/app/slink/images
    ports:
      - 3033:3000

**Comment by andrii-kryvoviaz** [comment]
@hypr88 are you running synology?

I assume that there might be a cookie issue. Make sure that your reverse proxy properly handles it and you have a valid SSL certificate set in place. 

A new release is going to be out soon, so I will look into the issue whether it could be fixed from the code and include a patch.

**Comment by hypr88** [comment]
Not Synology but equal (Ugreen Nas with Docker on it) 

This is also what i get from the logs - looks like its missing it 8080 locally in the container?!



2025-06-23 13:25:47,990 INFO exited: startup (exit status 0; expected)

TypeError: fetch failed

    at node:internal/deps/undici/undici:13502:13

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

  [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: localhost:8080, timeout: 10000ms)

      at onConnectTimeout (node:internal/deps/undici/undici:2602:28)

      at Immediate._onImmediate (node:internal/deps/undici/undici:2583:11)

      at process.processImmediate (node:internal/timers:491:21)

      at process.callbackTrampoline (node:internal/async_hooks:130:17) {

    code: 'UND_ERR_CONNECT_TIMEOUT'

  }

**Comment by andrii-kryvoviaz** [comment]
@hypr88 Thanks for the update. Are there any files generated in the mounted data folder? To eliminate any file permission issues.

**Comment by terrible-python-coder** [comment]
I have a very similar issue while trying to run this on TrueNAS 25.04 Fangtooth.

- I have Nginx Proxy Manager setup to reverse proxy from `https://slink.<mydomain.com>`, and it includes SSL certificate using Let's encrypt.
- The 2x volumes I created I have given unix permissions of 777. This was the only way I could get the login screen to function and create a new user.
- Now I successfully create users, but I can see no way to have the users approved. There is nothing displayed in the logs which gives an indication of how to approve.


This is my docker compose file:
```
services:
  slink:
    image: anirdev/slink:latest
    container_name: slink
    user: slink
    environment:
      # Your timezone
      - TZ=Australia/Sydney
      # Your application hostname (Required for cookies)
      - ORIGIN=https://slink.<mydomain.com>
      # Require user approval before they can upload images
      - USER_APPROVAL_REQUIRED=true
      # User password requirements
      - USER_PASSWORD_MIN_LENGTH=8
      - USER_PASSWORD_REQUIREMENTS=15 # bitmask of requirements
      # Maximum image size allowed to be uploaded (no more than 50M)
      - IMAGE_MAX_SIZE=15M
      # Storage provider to use (may require additional configuration variables for different providers, see below)
      - STORAGE_PROVIDER=local
    volumes:
      # Persist the database
      - /mnt/tank/configs/slink/db:/app/var/data
      # Persist the uploaded images
      - /mnt/tank/configs/slink/images:/app/slink/images
    ports:
      # Expose the application on port 3000
      - 3808:3000
networks: {}
```
this is the screen I'm greeted with, once adding a user:
![Image](https://github.com/user-attachments/assets/3e2c76ee-e03e-434c-a651-c5a96cba6bb7)
