### ISSUE TITLE
Secure cookies required, but TLS certificate not specified

### ISSUE THREAD

**Issue by yonas** [andrii-kryvoviaz/slink#51]
slink should accept a path to a TLS certificate pair, or generate one automatically if the setting is left empty.

```yaml
services:
  slink:
    image: anirdev/slink:latest
    container_name: slink
    environment:
      # Your timezone
      - TZ=America/Toronto

      # Your application hostname (Required for cookies)
      - ORIGIN=http://desktop.lan:3000

      # Require user approval before they can upload images
      - USER_APPROVAL_REQUIRED=false

      # User password requirements
      - USER_PASSWORD_MIN_LENGTH=8
      - USER_PASSWORD_REQUIREMENTS=15 # bitmask of requirements

      # Maximum image size allowed to be uploaded (no more than 50M)
      - IMAGE_MAX_SIZE=15M

      # Storage provider to use (may require additional configuration variables for different providers, see below)
      - STORAGE_PROVIDER=local
    volumes:
      # Persist the database
      - ./slink/var/data:/app/var/data
      # Persist the uploaded images
      - ./slink/images:/app/slink/images
    ports:
      # Expose the application on port 3000
      - '3000:3000'
```
